spring:
  datasource:
    url: jdbc:h2:mem:goflightsdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
