spring:
  application:
    name: "customers"
  datasource:
    url: jdbc:mysql://localhost:3306/customersdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active:
      - "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"


management:
  endpoints:
    web:
      exposure:
        include: "*"