spring:
  datasource:
    url: jdbc:h2:mem:goflightsdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"
  profiles:
    active:
      - "qa"

customers:
  message: "Customers Microservice for GoFlights Local Env"
  contact:
    name : "Will Wright"
    email: "wrightbrothers@goflights.io"
  phoneNumber:
    - (111)-234-5678