services:
  flights:
    image: "dineshsnkumar/flights:0.0.1-SNAPSHOT"
    container_name: flights-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - goflights
  customers:
    image: "dineshsnkumar/customers:0.0.1-SNAPSHOT"
    container_name: customers-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - goflights

networks:
  goflights:
    driver: "bridge"