spring:
  application:
    name: "apigateway"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000
      ssl: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true


info:
  app:
    name: "api-gateway"
    description: "Go Flights API Gateway"



resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 2

resilience4j.retry:
  instances:
    default:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2