server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:flightsdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: truespring.application.name=flights


flights:
  message: "Flights microservice for GoFlights"
  contact:
    name: "Will Wright"
    email: "wrightbrothers@info.com"
  phoneNumber:
    - (111)-234-1456