server:
  port: 9000
spring:
  application:
    name: "flights"
  datasource:
    url: jdbc:mysql://localhost:3307/flightsdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active:
      - "qa"
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"