server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:flightsdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: truespring.application.name=flights
