server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:flightsdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: truespring.application.name=flights
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"
  profiles:
    active:
      - "qa"




flights:
  message: "Flights microservice for GoFlights in DEV"
  contact:
    name: "Will Wright"
    email: "wrightbrothers@goflights.io"
  phoneNumber:
    - (111)-234-1456