server:
  port: 9000
spring:
  application:
    name: "flights"
  datasource:
    url: jdbc:h2:mem:flightsdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: truespring.application.name=flights
  profiles:
    active:
      - "qa"
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"