server:
  port: 8075

customers:
  message: "Customers microservice for GoFlights in PROD"
  contact:
    name: "Amelia Earhart- Product owner"
    email: "amelia@goflights.io"
  phoneNumber:
    - (111)-234-1456
