services:
#  rabbitmq:
#    image: rabbitmq:3.13-management
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    networks:
#      - goflights
#    environment:
#      SPRING_RABBITMQ_HOST: "rabbitmq"
  customersdb:
    container_name: 'customersdb'
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "customersdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  flightsdb:
    container_name: 'flightsdb'
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "flightsdb"
    extends:
      file: common-config.yml
      service: microservice-db-config


  configserver:
    image: "dineshsnkumar/configserver:0.0.3-SNAPSHOT"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config


  flights:
    image: "dineshsnkumar/flights:0.0.3-SNAPSHOT"
    container_name: flights-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "flights"
      SPRING_DATASOURCE_URL: "jdbc:mysql://flightsdb:3307/flightsdb"
    depends_on:
      flightsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  customers:
    image: "dineshsnkumar/customers:0.0.3-SNAPSHOT"
    container_name: customers-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "customers"
      SPRING_DATASOURCE_URL: "jdbc:mysql://customersdb:3306/customersdb"
    depends_on:
      customersdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  goflights:
    driver: "bridge"