spring:
  application:
    name: "messenger"
  cloud:
    stream:
      bindings:
        email-in-0:
          destination: email-topic
          group: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10

server:
  port: 9010
