apiVersion: v1
kind: ConfigMap
metadata:
  name: goflights-configmap
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
  CONFIGSERVER_APPLICATION_NAME: "configserver"
  EUREKA_APPLICATION_NAME: "eurekaserver"
  FLIGHTS_APPLICATION_NAME: "flights"
  CUSTOMERS_APPLICATION_NAME: "customers"
